(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "cider")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "gist")
(depends-on "helm")
(depends-on "helm-descbinds" :git "https://github.com/emacs-helm/helm-descbinds.git")
(depends-on "htmlize")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "prodigy")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "solarized-theme")
(depends-on "use-package")
